In [1]:
import numpy as np

In [2]:
# numpy
# 공학, 수학 대수학을 처리하는 용도로 사용
# scalar, vector, matrix, tensor

# array
---
리스트와 거의 비슷하다

In [9]:
# list : [1,2,4,'a','b']
# string : 'hello python'

L = [1,4,5,7]

test_arr = np.array(L)        # 리스트와 유사하다
test_arr

array([1, 4, 5, 7])

In [10]:
test_arr[1]        # indexing

4

In [14]:
test_arr[1:3]      # slicing

array([4, 5])

In [15]:
type(test_arr)

numpy.ndarray

In [17]:
test_arr.shape      # 원소가 4개인 1차원 array

(4,)

In [20]:
L = [1,2,3,'258']

In [21]:
np.array(L)        # 모든 원소가 동일한 데이터 타입으로 구성 => 연산 속도가 높다

array(['1', '2', '3', '258'], dtype='<U11')

In [25]:
L = [1, 2, 4, 3.14]     # 모든 원소가 실수형으로 바뀜
np.array(L)

array([1.  , 2.  , 4.  , 3.14])

In [26]:
L = [[1,2,4,5],[4,5,6,4],[8,6,4,3]]
L

[[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]]

In [28]:
np.array(L)         # matrix(행렬)

array([[1, 2, 4, 5],
       [4, 5, 6, 4],
       [8, 6, 4, 3]])

In [31]:
np.array(L).shape    # 2차원 matrix 3행 4열

(3, 4)

In [32]:
np.array(L).ndim      # 2차원(dimension)

2

In [33]:
t = [[[1,2,4,5],[4,5,6,4],[8,6,4,3]],
     [[1,2,4,5],[4,5,6,4],[8,6,4,3]]]
t

[[[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]],
 [[1, 2, 4, 5], [4, 5, 6, 4], [8, 6, 4, 3]]]

In [34]:
np.array(t)

array([[[1, 2, 4, 5],
        [4, 5, 6, 4],
        [8, 6, 4, 3]],

       [[1, 2, 4, 5],
        [4, 5, 6, 4],
        [8, 6, 4, 3]]])

In [35]:
np.array(t).shape          # 3차원 tensor   3행 4열 리스트가 2개있는 3차원 리스트

(2, 3, 4)

In [37]:
np.array(t).ndim

3

In [38]:
# reshape

In [40]:
L = [[1,2,4,5], [4,5,6,4]]
L

[[1, 2, 4, 5], [4, 5, 6, 4]]

In [41]:
test_mat = np.array(L)
test_mat

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [42]:
test_mat.shape

(2, 4)

In [43]:
test_mat.reshape(4,2)     # matrix

array([[1, 2],
       [4, 5],
       [4, 5],
       [6, 4]])

In [44]:
test_mat.reshape(8)      # 1차원(vector)으로 변경 가능

array([1, 2, 4, 5, 4, 5, 6, 4])

In [47]:
test_mat.reshape(2,2,2)    # 3차원(tensor)으로 변경 가능

array([[[1, 2],
        [4, 5]],

       [[4, 5],
        [6, 4]]])

In [49]:
test_mat.reshape(4,3)      # 단, 원소의 개수는 맞춰줘야한다

ValueError: cannot reshape array of size 8 into shape (4,3)

In [50]:
# np.array() : array로 형변환, datatype를 지정할 수 있다.

In [51]:
L = [[1,2,4,5], [4,5,6,4]]
np.array(L, float)

array([[1., 2., 4., 5.],
       [4., 5., 6., 4.]])

In [52]:
L = [[1,2,4,5], [4,5,6,4]]
np.array(L, str)

array([['1', '2', '4', '5'],
       ['4', '5', '6', '4']], dtype='<U1')

In [53]:
# indexing

In [54]:
tm = np.array(L)
tm

array([[1, 2, 4, 5],
       [4, 5, 6, 4]])

In [56]:
# arr[row_index, col_index]

In [57]:
tm[1,2]

6

In [58]:
tm[1][2]

6

In [59]:
tm[0,2] = 10
tm

array([[ 1,  2, 10,  5],
       [ 4,  5,  6,  4]])

In [60]:
tm = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
tm[1,2]

8

In [63]:
tm[0,1:3]

array([2, 3])

In [64]:
tm[:,3]

array([4, 9])

In [65]:
tm[:,3:]

array([[ 4,  5],
       [ 9, 10]])

In [71]:
tm[:,1:4:2]

array([[2, 4],
       [7, 9]])

In [72]:
# arange

In [73]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [75]:
list(np.arange(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [76]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [77]:
list(range(1,11,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [83]:
print(list(np.arange(1,11,0.2)))    # arange를 사용하면 step를 정교하게 줄 수 있다.

[1.0, 1.2, 1.4, 1.5999999999999999, 1.7999999999999998, 1.9999999999999998, 2.1999999999999997, 2.3999999999999995, 2.5999999999999996, 2.8, 2.9999999999999996, 3.1999999999999993, 3.3999999999999995, 3.5999999999999996, 3.7999999999999994, 3.999999999999999, 4.199999999999999, 4.3999999999999995, 4.6, 4.799999999999999, 4.999999999999999, 5.199999999999999, 5.399999999999999, 5.599999999999999, 5.799999999999999, 5.999999999999999, 6.199999999999999, 6.399999999999999, 6.599999999999999, 6.799999999999999, 6.999999999999998, 7.199999999999998, 7.399999999999999, 7.599999999999999, 7.799999999999999, 7.999999999999998, 8.2, 8.399999999999999, 8.599999999999998, 8.799999999999997, 8.999999999999998, 9.199999999999998, 9.399999999999999, 9.599999999999998, 9.799999999999997, 9.999999999999998, 10.199999999999998, 10.399999999999999, 10.599999999999998, 10.799999999999997]


In [87]:
print([round(i,2) for i in np.arange(1,11,0.2)])

[1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.2, 4.4, 4.6, 4.8, 5.0, 5.2, 5.4, 5.6, 5.8, 6.0, 6.2, 6.4, 6.6, 6.8, 7.0, 7.2, 7.4, 7.6, 7.8, 8.0, 8.2, 8.4, 8.6, 8.8, 9.0, 9.2, 9.4, 9.6, 9.8, 10.0, 10.2, 10.4, 10.6, 10.8]


In [88]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Operation

In [89]:
tm = np.arange(30).reshape(5,6)
tm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [90]:
tm.sum()

435

In [92]:
tm.mean()

14.5

In [93]:
tm.sum(axis=0)   # axis=0 : col끼리 연산(세로방향)

array([60, 65, 70, 75, 80, 85])

In [95]:
tm.sum(axis=1)   # axis=1 : low끼리 연산(가로방향)

array([ 15,  51,  87, 123, 159])

In [96]:
tm.max(axis=0)

array([24, 25, 26, 27, 28, 29])

In [98]:
tm.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [99]:
tm.min(axis=1)

array([ 0,  6, 12, 18, 24])

In [101]:
tm.std(axis = 0)       # 표준편차

array([8.48528137, 8.48528137, 8.48528137, 8.48528137, 8.48528137,
       8.48528137])

### element wise peration : 원소간의 연산

In [103]:
arr_a = np.arange(6).reshape(2,3)
arr_b = np.arange(6).reshape(2,3)

In [104]:
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
arr_b

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
arr_a + arr_b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [108]:
arr_a - arr_b

array([[0, 0, 0],
       [0, 0, 0]])

### Broadcasting
---
shape이 서로 다른 array간에 연산을 하는 경우, shape이 작은 array의 shape이 확장이 되어 element간에 연산을 하게 된다.

In [113]:
arr_a + 10       # scalar가 2by3 matrix로 확장되어서 element wise 연산을 한다

# arr_a + [[10,10,10], [10,10,10]]

array([[10, 11, 12],
       [13, 14, 15]])

In [114]:
arr_a

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
arr_v = np.array([1,2,4])
arr_v

array([1, 2, 4])

In [116]:
arr_a + arr_v

array([[1, 3, 6],
       [4, 6, 9]])

### Boolean Indexing
---
boolean array를 index로 하여 True에 해당하는 값만을 추출

array의 길이와 boolean array의 길이가 같아야 한다

In [118]:
ta = np.array([1,4,5,6,3,5,6])

In [119]:
# ta에서 5 이상인 값만 출력

In [122]:
ta >= 5 

array([False, False,  True,  True, False,  True,  True])

In [126]:
ta[ta >= 5]

array([5, 6, 5, 6])

In [127]:
# ta에서 짝수만 출력하시요

In [128]:
ta[ta % 2 == 0]

array([4, 6, 6])

In [130]:
np.array(list(filter(lambda x : x % 2 == 0, ta)))

array([4, 6, 6])

In [131]:
# 1 ~ 100 사이의 정수에서 20보다 크고 30보다 작은 3의 배수를 출력

In [148]:
ta = np.arange(1,101)
ta = ta[ta > 20]
ta = ta[ta < 30]
ta = ta[ta % 3 == 0]
ta

array([21, 24, 27])

In [155]:
ta = np.arange(1,101)
ta[(ta > 20) & (ta < 30) & (ta % 3 == 0)]

array([21, 24, 27])